CREATE TABLE `brote` (
  `idbrote` int NOT NULL AUTO_INCREMENT,
  `folionotinmed` varchar(15) NOT NULL,
  `fechnotinmed` datetime NOT NULL,
  `tipoevento` varchar(45) NOT NULL,
  `unidadnotif` varchar(45) NOT NULL,
  `institucion` varchar(45) NOT NULL,
  `fechinicio` datetime NOT NULL,
  `fechnotifica` datetime NOT NULL,
  `diagsospecha` varchar(45) NOT NULL,
  `jurisdiccion` varchar(45) NOT NULL,
  `municipio` varchar(45) NOT NULL,
  `localidad` varchar(45) NOT NULL,
  `pobmascexp` int NOT NULL,
  `pobfemexp` int NOT NULL,
  `casosprob` int NOT NULL,
  `casosconf` int NOT NULL,
  `defunciones` int NOT NULL,
  `nota` varchar(200) NOT NULL,
  `fechultimocaso` datetime NOT NULL,
  `fechalta` datetime NOT NULL,
  `resultado` varchar(45) NOT NULL,
  `folioaltanotin` varchar(45) NOT NULL,
  `fechaltanotin` datetime NOT NULL,
  PRIMARY KEY (`idbrote`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COMMENT='							'